### ISSUE TITLE
Provide pure-floss build flavor

### ISSUE THREAD

**Issue by ghost** [mattgmg1990/miracast-widget#3]
The app now uses Google's proprietary play-services. Could you provide a completely free build flavor?

**Comment by mattgmg1990** [comment]
Sure, what form would that take, though? A new repository? You can restore the application before I introduced the play services dependency just by checking out https://github.com/mattgmg1990/miracast-widget/commit/01b9d5533f494e998b218f27eb5a8d8ffddb9908, is that enough?

**Comment by IzzySoft** [comment]
As you use gradle, a "foss-flavor" would probably be the easiest approach. That way it's done by several other apps sharing the same issue. See [here](https://developer.android.com/studio/build/build-variants#product-flavors) for details on flavors and how to set them up.

If it's not possible via a gradle flavor for one reason or another, a "foss-branch" could work as well. A separate repository will not be necessary.
