### ISSUE TITLE
Bad gradle version

### ISSUE THREAD

**Issue by bgarr33434** [mattgmg1990/miracast-widget#5]
Gradle is the bane of my existence.  This says gradle 2.11 is required and compiler says 2.11 is too old a plugin.

**Comment by mattgmg1990** [comment]
It probably would be pretty easy to update it to a newer version. Try it and submit a pull request?

**Comment by bgarr33434** [comment]
whew, been working on this for 4 days.  By deleting all of the gradle files and importing, I can get it to compile, but not to output apk files.  I've also tried creating a new project and copying files over, but that didn't work either.
